In [1]:
import torch

In [129]:
x = torch.randn(1,1, requires_grad=True)

In [130]:
x

tensor([[-0.7473]], requires_grad=True)

In [131]:
x.grad

In [132]:
y = x * 2

In [133]:
y

tensor([[-1.4947]], grad_fn=<MulBackward0>)

In [134]:
z = torch.mean(y)

In [135]:
z.backward()

In [136]:
x.grad

tensor([[2.]])

In [137]:
x.data

tensor([[-0.7473]])

In [138]:
x.data.add_(x.grad)

tensor([[1.2527]])

In [139]:
x.data

tensor([[1.2527]])

In [140]:
x.grad

tensor([[2.]])

In [141]:
x = x * 3 + x.grad

In [142]:
x.data

tensor([[5.7580]])

In [143]:
x.grad

In [147]:
x.requires_grad

True

In [148]:
x.grad

In [149]:
x

tensor([[5.7580]], grad_fn=<AddBackward0>)

In [150]:
x1 = x

In [151]:
x1

tensor([[5.7580]], grad_fn=<AddBackward0>)

In [152]:
x = x + 2

In [153]:
x

tensor([[7.7580]], grad_fn=<AddBackward0>)

In [154]:
x1

tensor([[5.7580]], grad_fn=<AddBackward0>)

In [155]:
x1 = x

In [156]:
x.add_(1)

tensor([[8.7580]], grad_fn=<AddBackward0>)

In [157]:
x1

tensor([[8.7580]], grad_fn=<AddBackward0>)

In [158]:
x.add_(2)

tensor([[10.7580]], grad_fn=<AddBackward0>)

In [159]:
x1

tensor([[10.7580]], grad_fn=<AddBackward0>)

In [175]:
x = torch.randn(1,1, requires_grad=True)

In [176]:
y = x

In [177]:
z = x * 2

In [178]:
z.backward()

In [179]:
x.grad

tensor([[2.]])

In [180]:
y.grad

tensor([[2.]])

In [181]:
x = 3 * x + x.grad

In [182]:
x.grad

In [183]:
y.data

tensor([[1.1591]])

In [184]:
y.grad

tensor([[2.]])

In [185]:
x.backward()

In [186]:
y.grad

tensor([[5.]])

When updating a weight or something, if one use x = x + ... , PyTorch create new root of computing graph; is one use x.add_( ... ) then PyTorch don't extend the graph. The former induce waste of memory, i.e. objects that's are not pointed by vatiables anymore; ~~requires_grad also become False~~. The later is semantically correct and induce no memory waste.

In [187]:
x.requires_grad

True