In [1]:
import torch

In [2]:
x = torch.ones(2,2)

In [3]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [4]:
x

tensor([[1., 1.],
        [1., 1.]])

In [11]:
x.requires_grad = True

In [13]:
y = x * x

In [14]:
z = 0.5 * y

In [19]:
w = torch.mean(z)

In [20]:
w.backward()

In [21]:
x.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [22]:
x = x + x.grad * 0.1

In [24]:
x.requires_grad

True

In [26]:
x.grad

In [40]:
def make_mean(x):
    return torch.mean(x * x + 2 * x)

In [33]:
z = make_z()

In [34]:
z.backward()

In [35]:
x.grad

In [36]:
z = torch.mean(x * x)

In [37]:
z.backward()

In [38]:
x.grad

In [39]:
z

tensor(1.0506, grad_fn=<MeanBackward0>)

### x.data.add_(x.grad)
x.add_() induce err.

In [128]:
x1 = torch.ones(3,3, requires_grad=True)

In [129]:
x1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [130]:
x1.grad_fn

In [131]:
z1 = make_mean(x1)

In [132]:
z1.backward()

In [133]:
x1.grad

tensor([[0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444]])

In [134]:
#x1 = x1 + x1.grad
x1.add_(x1.grad)

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [135]:
x1.data.add_(x1.grad)

tensor([[1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444]])

In [136]:
x1

tensor([[1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444]], requires_grad=True)

In [137]:
x1.grad

tensor([[0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444]])

In [138]:
x1.requires_grad

True

In [139]:
z1 = make_mean(x1)

In [140]:
z1.backward()

In [141]:
x1

tensor([[1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444]], requires_grad=True)

In [142]:
x1.grad

tensor([[0.9877, 0.9877, 0.9877],
        [0.9877, 0.9877, 0.9877],
        [0.9877, 0.9877, 0.9877]])

### x = x + x.grad

In [143]:
x1 = torch.ones(3,3, requires_grad=True)

In [144]:
x1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [145]:
x1.grad_fn

In [146]:
z1 = make_mean(x1)

In [147]:
z1.backward()

In [148]:
x1.grad

tensor([[0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444]])

In [149]:
x1 = x1 + x1.grad

In [150]:
x1

tensor([[1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444]], grad_fn=<AddBackward0>)

In [151]:
x1.grad

x1.grad disappeared!

In [152]:
x1.requires_grad

True

In [153]:
z1 = make_mean(x1)

In [154]:
z1.backward()

In [155]:
x1

tensor([[1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444]], grad_fn=<AddBackward0>)

In [156]:
x1.grad

x1.grad disappeared!

### x.data = x + x.grad

In [157]:
x1 = torch.ones(3,3, requires_grad=True)

In [158]:
x1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [159]:
x1.grad_fn

In [160]:
z1 = make_mean(x1)

In [161]:
z1.backward()

In [162]:
x1.grad

tensor([[0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444]])

In [163]:
x1.data = x1 + x1.grad

In [164]:
x1

tensor([[1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444]], requires_grad=True)

In [165]:
x1.grad

tensor([[0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444]])

x1.grad exists.

In [166]:
x1.requires_grad

True

In [167]:
z1 = make_mean(x1)

In [168]:
z1.backward()

In [169]:
x1

tensor([[1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444],
        [1.4444, 1.4444, 1.4444]], requires_grad=True)

In [170]:
x1.grad

tensor([[0.9877, 0.9877, 0.9877],
        [0.9877, 0.9877, 0.9877],
        [0.9877, 0.9877, 0.9877]])

In [171]:
x1.data = x1.data + x1.grad

Conclusion: when changing a value, just do it on x.data. using in-place or not doesn't matter.